In [3]:
# Import libraries
import pandas as pd  
import numpy as np   
import matplotlib.pyplot as plt 
import seaborn as sns 

# Load the dataset
df=pd.read_csv('../data/Crop_recommendation_ethiopia_real.csv')

# Basic info
print("Shape: ",df.shape)
print("\nFirst 5 rows:")
print(df.head())

Shape:  (3867, 29)

First 5 rows:
         Soilcolor    Ph        K       P     N        Zn       S    QV2M-W  \
0  Yellowish brown  5.81  738.231   5.401  0.23  2.976000  13.816  7.993333
1  Yellowish brown  5.43  606.382  10.478  0.23  3.077000  16.421  7.993333
2            brown  5.41  386.580   6.847  0.23  6.611000  16.557  7.993333
3              red  5.65  207.086   3.418  0.23  0.460181  16.075  7.993333
4              red  5.27  317.357  39.282  0.23  2.743000  12.558  7.993333

     QV2M-Sp    QV2M-Su  ...  PRECTOTCORR-W  PRECTOTCORR-Sp  PRECTOTCORR-Su  \
0  10.456667  11.963333  ...       2.073333            5.27       12.303333
1  10.456667  11.963333  ...       2.073333            5.27       12.303333
2  10.456667  11.963333  ...       2.073333            5.27       12.303333
3  10.456667  11.963333  ...       2.073333            5.27       12.303333
4  10.456667  11.963333  ...       2.073333            5.27       12.303333

   PRECTOTCORR-Au  WD10M  GWETTOP  CLOUD_AMT  WS2M_RANGE     PS   label
0            5.27   3.44     0.73      56.57        6.24  77.03  Barley
1            5.27   3.44     0.73      56.57        6.24  77.03  Barley
2            5.27   3.44     0.73      56.57        6.24  77.03  Barley
3            5.27   3.44     0.73      56.57        6.24  77.03  Barley
4            5.27   3.44     0.73      56.57        6.24  77.03  Barley

[5 rows x 29 columns]

In [4]:
print("\nColumn info: ")
print(df.info())

Column info:
<class 'pandas.DataFrame'>
RangeIndex: 3867 entries, 0 to 3866
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Soilcolor       3867 non-null   str
 1   Ph              3867 non-null   float64
 2   K               3867 non-null   float64
 3   P               3867 non-null   float64
 4   N               3867 non-null   float64
 5   Zn              3867 non-null   float64
 6   S               3867 non-null   float64
 7   QV2M-W          3867 non-null   float64
 8   QV2M-Sp         3867 non-null   float64
 9   QV2M-Su         3867 non-null   float64
 10  QV2M-Au         3867 non-null   float64
 11  T2M_MAX-W       3867 non-null   float64
 12  T2M_MAX-Sp      3867 non-null   float64
 13  T2M_MAX-Su      3867 non-null   float64
 14  T2M_MAX-Au      3867 non-null   float64
 15  T2M_MIN-W       3867 non-null   float64
 16  T2M_MIN-Sp      3867 non-null   float64
 17  T2M_MIN-Su      3867 non-null   float64
 18  T2M_MIN-Au      3867 non-null   float64
 19  PRECTOTCORR-W   3867 non-null   float64
 20  PRECTOTCORR-Sp  3867 non-null   float64
 21  PRECTOTCORR-Su  3867 non-null   float64
 22  PRECTOTCORR-Au  3867 non-null   float64
 23  WD10M           3867 non-null   float64
 24  GWETTOP         3867 non-null   float64
 25  CLOUD_AMT       3867 non-null   float64
 26  WS2M_RANGE      3867 non-null   float64
 27  PS              3867 non-null   float64
 28  label           3867 non-null   str
dtypes: float64(27), str(2)
memory usage: 876.2 KB
None

In [5]:
print("\n Missing values: ")
print(df.isnull().sum())

 Missing values:
Soilcolor         0
Ph                0
K                 0
P                 0
N                 0
Zn                0
S                 0
QV2M-W            0
QV2M-Sp           0
QV2M-Su           0
QV2M-Au           0
T2M_MAX-W         0
T2M_MAX-Sp        0
T2M_MAX-Su        0
T2M_MAX-Au        0
T2M_MIN-W         0
T2M_MIN-Sp        0
T2M_MIN-Su        0
T2M_MIN-Au        0
PRECTOTCORR-W     0
PRECTOTCORR-Sp    0
PRECTOTCORR-Su    0
PRECTOTCORR-Au    0
WD10M             0
GWETTOP           0
CLOUD_AMT         0
WS2M_RANGE        0
PS                0
label             0
dtype: int64

In [9]:
print("Exact duplicate rows:", df.duplicated().sum())

print("Duplicate feature rows, excluding label:",
      df.drop(columns=["label"]).duplicated().sum())

display(
    df[df.duplicated(keep=False)]
    .sort_values("label")
    .head(20)
)

Exact duplicate rows: 0
Duplicate feature rows, excluding label: 0

Empty DataFrame
Columns: [Soilcolor, Ph, K, P, N, Zn, S, QV2M-W, QV2M-Sp, QV2M-Su, QV2M-Au, T2M_MAX-W, T2M_MAX-Sp, T2M_MAX-Su, T2M_MAX-Au, T2M_MIN-W, T2M_MIN-Sp, T2M_MIN-Su, T2M_MIN-Au, PRECTOTCORR-W, PRECTOTCORR-Sp, PRECTOTCORR-Su, PRECTOTCORR-Au, WD10M, GWETTOP, CLOUD_AMT, WS2M_RANGE, PS, label]
Index: []

[0 rows x 29 columns]

In [10]:
numeric_cols = df.select_dtypes(include="number").columns

display(df[numeric_cols].describe().T)

,count,mean,std,min,25%,50%,75%,max
Ph,3867.0,5.857295,0.676690,4.300000,5.390000,5.780000,6.200000,8.500000
K,3867.0,324.284770,202.250133,41.134000,191.000000,282.000000,405.000000,2119.000000
P,3867.0,11.349588,34.141864,0.000000,2.000000,4.000000,7.920000,782.000000
N,3867.0,0.179153,0.066476,0.000262,0.131200,0.179884,0.230000,0.695600
Zn,3867.0,1.774094,1.460809,0.100000,1.100000,1.500000,2.060000,45.500000
S,3867.0,11.311625,5.542094,0.050000,7.305000,10.700000,14.195500,118.347000
QV2M-W,3867.0,8.346870,0.613948,7.183333,7.933333,8.383333,8.910000,9.723333
QV2M-Sp,3867.0,9.082508,0.790654,7.650000,8.403333,9.340000,9.480000,10.703333
QV2M-Su,3867.0,12.232020,0.894970,10.476667,11.430000,12.166667,12.836667,13.853333
QV2M-Au,3867.0,10.990747,0.993861,9.070000,10.150000,10.926667,11.433333,12.800000
T2M_MAX-W,3867.0,25.557973,4.250256,9.030000,25.206667,25.343333,28.113333,30.826667
T2M_MAX-Sp,3867.0,29.803876,2.317511,25.146667,28.870000,29.713333,31.156667,33.973333
T2M_MAX-Su,3867.0,24.686049,1.585957,23.060000,23.533333,23.650000,25.643333,28.243333
T2M_MAX-Au,3867.0,23.282298,1.609512,20.616667,22.280000,22.800000,24.430000,26.520000
T2M_MIN-W,3867.0,6.658860,1.933357,2.053333,5.760000,6.253333,8.533333,11.390000
T2M_MIN-Sp,3867.0,10.346157,2.304823,4.816667,9.296667,9.810000,12.253333,15.656667
T2M_MIN-Su,3867.0,11.582037,1.459263,8.433333,10.933333,11.206667,12.976667,14.726667
T2M_MIN-Au,3867.0,8.934315,2.046221,3.980000,8.260000,8.380000,10.700000,13.643333
PRECTOTCORR-W,3867.0,1.555862,0.691682,0.000000,0.910000,1.736667,2.073333,2.780000
PRECTOTCORR-Sp,3867.0,4.023404,1.117531,1.940000,3.246667,4.410000,5.203333,5.660000
PRECTOTCORR-Su,3867.0,14.517500,4.111199,4.836667,11.866667,16.620000,17.816667,19.920000
PRECTOTCORR-Au,3867.0,4.762687,1.394398,2.156667,3.463333,5.430000,5.823333,7.420000
WD10M,3867.0,71.579444,80.929898,0.060000,36.060000,68.940000,88.310000,354.880000
GWETTOP,3867.0,0.709028,0.055355,0.520000,0.690000,0.730000,0.740000,0.800000
CLOUD_AMT,3867.0,51.630709,16.328656,0.460000,48.620000,59.110000,59.110000,59.110000
WS2M_RANGE,3867.0,8.262413,9.661188,4.860000,5.410000,6.010000,6.240000,46.100000
PS,3867.0,78.426168,2.380380,74.170000,77.150000,78.250000,79.610000,83.760000

In [6]:
print("\nUnique crop(target classes): ")
print(df['label'].unique())
print("Number of unique crops: ", df['label'].nunique())

Unique crop(target classes):
<StringArray>
[    'Barley',       'Bean',    'Dagussa',     'Fallow',      'Maize',
 'Niger seed',        'Pea',     'Potato', 'Red Pepper',    'Sorghum',
       'Teff',      'Wheat']
Length: 12, dtype: str
Number of unique crops:  12

In [7]:
print("\nClass distribution: ")
print(df['label'].value_counts())

Class distribution:
label
Teff          1260
Maize          732
Wheat          715
Barley         503
Bean           253
Pea             94
Sorghum         72
Dagussa         71
Niger seed      64
Potato          48
Red Pepper      29
Fallow          26
Name: count, dtype: int64